certificateAuthorities:
  ord-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICSjCCAfCgAwIBAgIQdfbLK6yqlGEWU7WZ9XjF7jAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yMjAyMTIwNTM3NDFa
        Fw0zMjAyMTMwNTM3NDFaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzkQYAuMmpXWsZYdxQLz4i2+A
        Nw50BXNjiz0VDnBxWJUbezvYnro/w3PqX1us4Y02X+2zhNdwqfMIZRKt7TRjaKOB
        pzCBpDAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIL54IUqL/NWe30LO5RFCKi+Y
        AHLaXTh3CU9MDUdmE5k/MDcGA1UdEQQwMC6CCWxvY2FsaG9zdIIGb3JkLWNhgg1v
        cmQtY2EuZmFicmljhwR/AAABhwSnY9kBMAoGCCqGSM49BAMCA0gAMEUCIEgVXbqa
        i/rin3EF2NNxDtoVxRJXci7gIBrcxVlTp9iTAiEAoymUYqML4qNceOAATAq34UBZ
        4N6fTMTw2ELBAHy1LIU=
        -----END CERTIFICATE-----
    url: https://ord-ca.fabric:7054
  org1-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICTTCCAfOgAwIBAgIRAJF0nHmNU2hz964LtFrvOtwwCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjIwMjEyMDUzNzM3
        WhcNMzIwMjEzMDUzNzM3WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHfvuwNAu67gGTEq3kfwPrSc
        iL9BLWnwTInvha1JYXMuOPuJSrs5dlsG+VMtEBQ1h77GKYd4YbiuQW8ZQRcbzJWj
        gakwgaYwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCsEEZYe9ihhmmvKX6SDQt8
        yNYx3vmc8L0rIiY0u4GpJTA5BgNVHREEMjAwgglsb2NhbGhvc3SCB29yZzEtY2GC
        Dm9yZzEtY2EuZmFicmljhwR/AAABhwSnY9kBMAoGCCqGSM49BAMCA0gAMEUCIQDY
        SjVqG0LWtuO8lPHVb7PfhfBKMWmnAhyBgovuKHLdDgIgD10ip3roECDMDEnecNBn
        AuhY7tYw/9NvivZR5d1wW6A=
        -----END CERTIFICATE-----
    url: https://org1-ca.fabric:7054
  org2-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICTjCCAfOgAwIBAgIRANdf/s3aVrYQ1mLtUPfoz7QwCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjIwMjEyMDUzNzM5
        WhcNMzIwMjEzMDUzNzM5WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPBCd+GtbSU2PMEvm4siTv72
        DFU8bIjrilK6RMIYAL5PiJS49AWqcSAhoAsBPWXU5rjZhRE4R5FtfpTUul6Xiw2j
        gakwgaYwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCJFoMShXPTpYzSOOCmyIzR
        hIdtqso2+1GgHb67/LjkkjA5BgNVHREEMjAwgglsb2NhbGhvc3SCB29yZzItY2GC
        Dm9yZzItY2EuZmFicmljhwR/AAABhwSnY9kBMAoGCCqGSM49BAMCA0kAMEYCIQCZ
        shV+PQld5hi9Sjo8E3V2yCLC5qu2OOYmLHFVPFMo+wIhAJUTc8gsg3avM8KK2Ojk
        B7YGbe0xrMmuxiHsQki1i9pZ
        -----END CERTIFICATE-----
    url: https://org2-ca.fabric:7054
channels:
  _default:
    orderers: null
    peers:
      org1-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org1-peer2.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer2.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  organization: ""
name: hlf-network
orderers: null
organizations:
  Org1MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org1MSP
    orderers: null
    peers:
    - org1-peer1.fabric
    - org1-peer2.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUGI2XWviffQHmyTw6ywqwJc7S3R8wCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjIwMjEzMDYwMjAwWhcNMjMwMjEzMDYwNzAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAASfcyVUkVmK4WB6ETJ/zIbpQdljHOcXW2TB1Cw2wI9PTtd0clZi3Qb8
            nvTXGWbZxwKV4TGyr0k9mImUVgfXNKpko4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSUAB6stgRN7j9KxL5aZY9KFhJ5UjArBgNV
            HSMEJDAigCCXzW0ix1mjCY7pXW+tMHprjXF1lm+j2oPj1q+8mghRBDBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIEi+UegyCm2sDRwbpg8zRxKW9Opm5tpc3QWzUyHQtpEhAiALhwIaL7GxcdC8
            oFFJqs31Pg6o6N9rXxF4oY5iMFu+7Q==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgvZ3EGV2CKmKoiW79
            flUBksA06kYdXFR4fz25dwRkLGGhRANCAASfcyVUkVmK4WB6ETJ/zIbpQdljHOcX
            W2TB1Cw2wI9PTtd0clZi3Qb8nvTXGWbZxwKV4TGyr0k9mImUVgfXNKpk
            -----END PRIVATE KEY-----
  Org2MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org2MSP
    orderers: null
    peers:
    - org2-peer1.fabric
    - org2-peer2.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUWs2bScuX+qhszDHfycJsQhGlvV4wCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjIwMjEzMDYwNjAwWhcNMjMwMjEzMDYxMTAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAARIdTTOwfBbgUpije6DYaMv+Nm/0TeH/hikoNxuqkasogsRhzNFto2j
            pBMtXePa0xXF6crmo50X72v23CW6AMCUo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBR/BoDHvhjiH881Up7cRMwW4yF+KDArBgNV
            HSMEJDAigCCdV/rU2xHxKy0VE16wrl+v3O/JDyR+w9CCXkT2Ha5/eDBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIC2SeMbxs0XCtzC8Zrq5aSh2TdFFPFAuktrPxIdSgMjHAiBvTK2cHtPllxa0
            CoQMOM6r57YxHfdaZbpydQWP4PIlBQ==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgKdjCeq+X+AbRBDlu
            1ymhDukB2PNLCTXlS8GzOePYa/ShRANCAARIdTTOwfBbgUpije6DYaMv+Nm/0TeH
            /hikoNxuqkasogsRhzNFto2jpBMtXePa0xXF6crmo50X72v23CW6AMCU
            -----END PRIVATE KEY-----
peers:
  org1-peer1.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRALDyEJJpZmpjxzMcgI0r/dswCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjIwMjEyMDUzNzM3WhcNMzIwMjEzMDUzNzM3WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABABWsoWSo0sM1ZUT
        DqOfCAj+hVjBQEkGngy6MBs+5XJhRtMiUnb4yh5U5sva3nH+hOjpz1dbSzQ0zLee
        dOw8v6ajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgaTyiCQeKzwAJh2RW
        obVyaFmPH6McB0OXlX5b2LCy/pcwCgYIKoZIzj0EAwIDSAAwRQIgTmgSU7BBNv5g
        OrVVRhk5JfMynG3O9lzm0fwL+jNw620CIQC7r8HFShKwgRo4WeiU0xWRiK+RqHp5
        fuwWKV3d0dcIMw==
        -----END CERTIFICATE-----
    url: grpcs://org1-peer1.fabric:7051
  org1-peer2.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRALDyEJJpZmpjxzMcgI0r/dswCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjIwMjEyMDUzNzM3WhcNMzIwMjEzMDUzNzM3WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABABWsoWSo0sM1ZUT
        DqOfCAj+hVjBQEkGngy6MBs+5XJhRtMiUnb4yh5U5sva3nH+hOjpz1dbSzQ0zLee
        dOw8v6ajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgaTyiCQeKzwAJh2RW
        obVyaFmPH6McB0OXlX5b2LCy/pcwCgYIKoZIzj0EAwIDSAAwRQIgTmgSU7BBNv5g
        OrVVRhk5JfMynG3O9lzm0fwL+jNw620CIQC7r8HFShKwgRo4WeiU0xWRiK+RqHp5
        fuwWKV3d0dcIMw==
        -----END CERTIFICATE-----
    url: grpcs://org1-peer2.fabric:7051
  org2-peer1.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRAIsJn3gVVbld2KPRTZ9kVrUwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjIwMjEyMDUzNzM5WhcNMzIwMjEzMDUzNzM5WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO6dqiB7GR6OTeGf
        nS+dHvE/Mh68G0Jug24EIm2iLn1FN+wsZb/Tw8brGDNz1H20iilV8hmMkGYHpjoc
        VkzZ4tWjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgej7FOcawq+srWFC3
        TikeOHIw3uHo1VB4qS9uvGOvQ80wCgYIKoZIzj0EAwIDSAAwRQIgK92/M2lTcUR3
        NdccuO2hiZDcxvCV7VHE20KvNHcSu0sCIQCuKoAoZSAvRkgudMs6qyCGGNzbaNzL
        ouSd5fMybqSt5w==
        -----END CERTIFICATE-----
    url: grpcs://org2-peer1.fabric:7051
  org2-peer2.fabric:
    grpcOptions:
      allow-insecure: false
      hostnameOverride: ""
      ssl-target-name-override: ""
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeygAwIBAgIRAIsJn3gVVbld2KPRTZ9kVrUwCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjIwMjEyMDUzNzM5WhcNMzIwMjEzMDUzNzM5WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO6dqiB7GR6OTeGf
        nS+dHvE/Mh68G0Jug24EIm2iLn1FN+wsZb/Tw8brGDNz1H20iilV8hmMkGYHpjoc
        VkzZ4tWjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgej7FOcawq+srWFC3
        TikeOHIw3uHo1VB4qS9uvGOvQ80wCgYIKoZIzj0EAwIDSAAwRQIgK92/M2lTcUR3
        NdccuO2hiZDcxvCV7VHE20KvNHcSu0sCIQCuKoAoZSAvRkgudMs6qyCGGNzbaNzL
        ouSd5fMybqSt5w==
        -----END CERTIFICATE-----
    url: grpcs://org2-peer2.fabric:7051
version: 1.0.0
